### ISSUE TITLE
[Bug] NavBar onClick Triggers on Page Load For All Items 

### ISSUE THREAD

**Issue by j14y** [creativetimofficial/black-dashboard-react#10]
### Version
1.0.0
### Reproduction link
N/a
### Operating System
MacOS
### Device
Macbook Pro 2017
### Browser & Version
Chrome 75.0.3770.100
### Steps to reproduce
1. Add an onClick event to a ReactStrap DropdownItem (add in a logging statement for example)
2. Go to the page or refresh the page
### What is expected?
The page loads, and onClick events trigger only when clicked by the user.
### What is actually happening?
Every time the user refreshes or enters a view in the dashboard, DropDownItem onClick events execute for every item, irrespective of the user clicking on the item or not.

---
### Additional comments
This may be an issue with Reactstrap, but I'm uncertain.

**Comment by einazare** [comment]
Hello there, @jordychetty ,

Thank you for your interest in working with our products.
Could you please show me a snippet code of your Dropdownitem with the onClick function?

Best,
Manu

**Comment by j14y** [comment]
@EINazare, here's the snippet you've requested. The same behaviour also occurs when using the toggle prop.

<b>AdminNavBar.jsx</b>
```
                 <DropdownMenu className="dropdown-navbar" right tag="ul">
                    <NavLink tag="li">
                      <DropdownItem className="nav-item">Profile</DropdownItem>
                    </NavLink>
                    <NavLink tag="li">
                      <DropdownItem className="nav-item">Settings</DropdownItem>
                    </NavLink>
                    <DropdownItem divider tag="li" />
                    <NavLink tag="li">
                      <DropdownItem className="nav-item" onClick={console.log('called on load')}>Log out</DropdownItem> {/*onClick added to this line*/}
                    </NavLink>
                  </DropdownMenu>
```

Although it affects the Dropdown and child DropdownItems, all calls within the render method are called on load. As an example:

<b>AdminNavBar.jsx</b>
```
 render() {
    return (
      <>
        <Button onClick={console.log('called on load')}> {/* debug statement will print to console */}
          Debug
        </Button>
        <Navbar
{/* ... rest of navbar code ... */}
```

**Comment by einazare** [comment]
Hello there, @jordychetty ,

In react you shouldn't have code like this:
```
onClick={console.log('called on load')}
```
This will determinate the call of the given function on page load.
What you need, is to change that code to this:
```
onClick={() => { console.log('called on load'); } }
```
Please read the official docs of ReactJS about event triggering: https://reactjs.org/docs/handling-events.html

Best,
Manu
