### ISSUE TITLE
No View on Live Website

### ISSUE THREAD

**Issue by danialshakeel** [creativetimofficial/black-dashboard-react#11]
I am receiving this certain error on all of my projects which are using this template. Their is now view for the website, just a blank page on live version.

Super expression must either be null or a function

![Screen Shot 2019-09-23 at 3 45 50 PM](https://user-images.githubusercontent.com/40662656/65419938-42562000-de19-11e9-9c12-32679db8b251.png)

**Comment by einazare** [comment]
Hello there, @danialshakeel 

Thank you for your interest in working with our products.
It seems that you haven't respected our ISSUE_TEMPLATE, so we are going to close it.
Please add a new comment here, or open a new issue, by filling the mentioned ISSUE_TEMPLATE and please be sure that your issue title is a very small description of your issue as well.
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/black-dashboard-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->

```

All the best,
Manu
Developer @ Creative-Tim.com (http://creative-tim.com/)
