### ISSUE TITLE
[Feature Request] Encapsulate Changing background and theme colors via top-level React Context components

### ISSUE THREAD

**Issue by Tsiou** [creativetimofficial/black-dashboard-react#17]
### What is your enhancement?
I would suggest encapsulating the logic and types of available options into their own contexts and components, allowing the easier addition/usage of said options as well as further additions to it.

That way it would be far easier for people to see what the current options are and reuse them in their design, as well as add/remove some or reuse them in more components.

I have already done the work for the change to be incorporated in my own fork, found here: [adding-contexts-for-theme/background](https://github.com/Tsiou/black-dashboard-react/tree/adding-contexts-for-theme/background-issues)

If there is no need for the change, just close the issue.

If something needs to be changed in order for the changes to be incorporated, let me know and I'll change it.

**Comment by einazare** [comment]
Hey there, @Tsiou ,

Thank you for your feedback.
That actually sounds really good.
Right now we can't make these changes, if you have time, you can open a PR with the mentioned changes and we'll add them on our next update.

Thank you,
Manu
