### ISSUE TITLE
[Bug] Double invocation of onClick

### ISSUE THREAD

**Issue by jektvik** [creativetimofficial/black-dashboard-react#19]
### Version
1.1.0
### Reproduction link
https://demos.creative-tim.com/black-dashboard-react/#/admin/dashboard
### Operating System
windows
### Device
pc
### Browser & Version
Chrome Version 81.0.4044.113
### Steps to reproduce
On the template dashboard click either of Accounts Purchases or Sessions
Debug the onClick handler and observe that on each of these buttons it fires twice
### What is expected?
The onClick function should be invoked once
### What is actually happening?
The onClick function is invoked twice

---
### Solution
Removing input from inside the button component removes the problem but it also removes ui

**Comment by EINazare** [comment]
Hello there, @jekusz ,

Thank you for your interest in working with our products.
Could you please share with us how did you debug the onClick handler?

Best,
Manu

**Comment by einazare** [comment]
Hello there, @jekusz ,

Thank you for your interest in working with our products.
Please go inside `src/views/Dashboard.js` and delete the following bits of code:
```
                          <input
                            defaultChecked
                            className="d-none"
                            name="options"
                            type="radio"
                          />
```
```
                          <input
                            className="d-none"
                            name="options"
                            type="radio"
                          />
```
And 
```
                          <input
                            className="d-none"
                            name="options"
                            type="radio"
                          />
```
Alternatively, you can change the following code from:
```
  setBgChartData = name => {
    this.setState({
      bigChartData: name
    });
  };
```
to:
```
  setBgChartData = (event,name) => {
    event.preventDefault();
    this.setState({
      bigChartData: name
    });
  };
```
And the following codes:
```
onClick={() => this.setBgChartData("data1")}
```
```
onClick={() => this.setBgChartData("data2")}
```
```
onClick={() => this.setBgChartData("data3")}
```
To:
```
onClick={(e) => this.setBgChartData(e,"data1")}
```
```
onClick={(e) => this.setBgChartData(e,"data2")}
```
```
onClick={(e) => this.setBgChartData(e,"data3")}
```

Best,
Manu

**Comment by jektvik** [comment]
I suppose the reason for the issue are the <input> tags inside the <button> elements. Though deleting them will remove some of the functionality they carry ? I like the preventDefault option better until it gets a good fix. Thanks!
