### ISSUE TITLE
App does not compile after npm install

### ISSUE THREAD

**Issue by quickshiftin** [creativetimofficial/black-dashboard-react#2]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ X ] I am running the latest version
- [ X ] I checked the documentation and found no answer
- [ X ] I checked to make sure that this issue has not already been filed
- [ X ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Per the documentation after downloading I run

* `npm install`
* `npm start`

Expect the app to start up.

# Current Behavior

The app fails to compile

# Failure Information (for bugs)

## Steps to Reproduce

1. Download, unzip
2. cd into unpacked directory
3. npm install
4. npm start

## Context

I'm running Ubuntu 16.04, node V8.12.0

## Failure Logs

```bash
Failed to compile.

./src/index.js
Module not found: Can't resolve 'assets/css/nucleo-icons.css' in '/home/nathan/gitRepos/peculator/black-dash-unpack/src'
```

NOTE: This file is there...
```bash
nathan@maximus:~/gitRepos/peculator/black-dash-unpack$ ls /home/nathan/gitRepos/peculator/black-dash-unpack/src/assets/css/nucleo-icons.css
/home/nathan/gitRepos/peculator/black-dash-unpack/src/assets/css/nucleo-icons.css
nathan@maximus:~/gitRepos/peculator/black-dash-unpack$ echo $?
0
```

**Comment by quickshiftin** [comment]
I've upgraded to node 11.7.0 and still get the error. It looks like node is failing to import a css file; here is the line it doesn't like

```javascript
import "assets/css/nucleo-icons.css";
```

It looks like the server does start, but when I visit the page I see this:
```
Failed to compile
./src/index.js
Module not found: Can't resolve 'assets/css/nucleo-icons.css' in '/home/nathan/gitRepos/peculator/black-dash-unpack/src'
This error occurred during the build time and cannot be dismissed.
```

**Comment by quickshiftin** [comment]
Solved by prepending `NODE_PATH=./src` to the `start` script in _package.json_.

**Comment by Gabswim** [comment]
you should not have to add NODE_PATH=./src. It is a hack to because all the import of the project are absolute and should be relative. 
Instead of this:
~import "assets/css/nucleo-icons.css"~;
should be this
**import "./assets/css/nucleo-icons.css";**

**Comment by einazare** [comment]
Hello there, @Gabswim ,

Why do you believe that this is a hack? (using absolute imports)
Also, you can solve this by using the jsconfig.json file.
You can take a look at this product to see how to configure it: https://github.com/creativetimofficial/paper-kit-react

Best,
Manu
