### ISSUE TITLE
[Feature Request] how to use rtl theme

### ISSUE THREAD

**Issue by Heshki** [creativetimofficial/black-dashboard-react#20]
### What is your enhancement?
Hi, i need to use rtl theme this template but show me a blank page.
please help me.
thanks.

**Comment by einazare** [comment]
Hello there, @Heshki ,

Is this a BUG report, or a FEATURE request?
Or is it a help wanted type of issue?
As far as I can see, on our live preview: https://demos.creative-tim.com/black-dashboard-react/#/rtl/rtl-support
The RTL page works as expected.

Please provide additional information.

Best,
Manu
