### ISSUE TITLE
[Bug] Errors on lodash.js, chunk.css and chunk.js requests, on Production.

### ISSUE THREAD

**Issue by JanderSilv** [creativetimofficial/black-dashboard-react#23]
### Version
1.1.0
### Reproduction link
https://elegant-tereshkova-e65e39.netlify.app/
### Operating System
Windows
### Device
Laptop
### Browser & Version
Firefox - 80.0
### Steps to reproduce
Open the Network tab of the Browser's Dev Tools and see the Network requests that failed.
### What is expected?
That the application shows up the Login Screen
### What is actually happening?
It's crashing the application.

---
### Solution
I don't have any ideas.

**Comment by einazare** [comment]
Hello there, @JanderSilv ,

If you delete the homepage prop from inside the package.json, do yo still have the issue? Or maybe you need to configure it for your own domain name.

Best,
Manu

**Comment by JanderSilv** [comment]
Yeah, the solution was delete the homepage prop. Thanks for your help and your hard work with the Black-Dashboard.
