### ISSUE TITLE
[Feature Request] How can I add this amazing template to an existing project?

### ISSUE THREAD

**Issue by AmmarMohamadIsmaeel** [creativetimofficial/black-dashboard-react#24]
### What is your enhancement?
Hello, I am working on a project for two months and now I want to create a dashboard page. How Can I add this template to my project? I tried copying all the components but the styles in my already done pages were ruined.
 Thank you

**Comment by einazare** [comment]
Hello there, @AmmarMohamadIsmaeel ,

Please take a look at this thread for another one of our products: https://github.com/creativetimofficial/ct-material-dashboard-pro-react/issues/50#issuecomment-407030675

Best,
Manu
