### ISSUE TITLE
[Feature Request] Persistence theme and background color.

### ISSUE THREAD

**Issue by hadialqattan** [creativetimofficial/black-dashboard-react#27]
### What is your enhancement?
I think it would be great if we made the theme and the background color persistence using the ```localStorage```. 

(now with every page loading they reset to default values).

NOTE: if you would like me to work on that, please assign this issue to me.

**Comment by einazare** [comment]
Hello there, @hadialqattan ,

We will close this issue since if we were to do so, we would have to ask permission from our users for cookie settings.

Best,
Manu

**Comment by hadialqattan** [comment]
> Hello there, @hadialqattan ,
> 
> We will close this issue since if we were to do so, we would have to ask permission from our users for cookie settings.
> 
> Best,
> Manu

Hi, I got your point, but I think here we don't need to notify the user about using the `localStorage` because we're not tracking his personal data it just a way to store some settings in key-value pare to enhance the UX of the template.



_Have a nice day!_
