### ISSUE TITLE
[Bug] Infinite scrolldown!

### ISSUE THREAD

**Issue by hadialqattan** [creativetimofficial/black-dashboard-react#28]
### Version
1.2.0
### Reproduction link
https://demos.creative-tim.com/black-dashboard-react/#/admin/dashboard
### Operating System
Windows 10
### Device
Desktop
### Browser & Version
Google Chrome 88
### Steps to reproduce
1. open the live preview.
2. scroll down using your mouse (don't use the scrollbar).
3. you'll see the page scrolls inappropriately.
### What is expected?
The page should stop scrolling when we reach the footer.
### What is actually happening?
The page doesn't stop scrolling infinitely!

---

**Comment by einazare** [comment]
Hello there, @hadialqattan ,

Is this issue happening here as well: https://demos.creative-tim.com/black-dashboard-react/#/admin/dashboard ?

Best,
Manu

**Comment by hadialqattan** [comment]
> Hello there, @hadialqattan ,
> 
> Is this issue happening here as well: https://demos.creative-tim.com/black-dashboard-react/#/admin/dashboard ?
> 
> Best,
> Manu

Hi, yes, I'm just scrolling using my mouse.

![image](https://user-images.githubusercontent.com/50833881/107938458-7c880a80-6f96-11eb-8dee-e0fdbc521c53.png)

_NOTE: the scroll doesn't stop at this level, I can continue scrolling until seeing a blank page._

**Comment by hadialqattan** [comment]
GIF:
![Black Dashboard React by Creative Tim - Google Chrome 2021-02-15 14-12-09 (online-video-cutter com)](https://user-images.githubusercontent.com/50833881/107939796-4b103e80-6f98-11eb-8372-18ea4bf90501.gif)
_sorry for the low resolution!_

**Comment by einazare** [comment]
Hello again, @hadialqattan ,

At the moment, the only solution I can think of is this one:
- Go inside `src/layouts/Admin/Admin.js` and delete the following bits of code:
```
// javascript plugin used to create scrollbars on windows
import PerfectScrollbar from "perfect-scrollbar";
```
```
var ps;
```
```
  React.useEffect(() => {
    if (navigator.platform.indexOf("Win") > -1) {
      document.documentElement.className += " perfect-scrollbar-on";
      document.documentElement.classList.remove("perfect-scrollbar-off");
      ps = new PerfectScrollbar(mainPanelRef.current, {
        suppressScrollX: true,
      });
      let tables = document.querySelectorAll(".table-responsive");
      for (let i = 0; i < tables.length; i++) {
        ps = new PerfectScrollbar(tables[i]);
      }
    }
    // Specify how to clean up after this effect:
    return function cleanup() {
      if (navigator.platform.indexOf("Win") > -1) {
        ps.destroy();
        document.documentElement.classList.add("perfect-scrollbar-off");
        document.documentElement.classList.remove("perfect-scrollbar-on");
      }
    };
  });
```
```
    if (navigator.platform.indexOf("Win") > -1) {
      let tables = document.querySelectorAll(".table-responsive");
      for (let i = 0; i < tables.length; i++) {
        ps = new PerfectScrollbar(tables[i]);
      }
    }
```

The issue comes from the PerfectScrollbar plugin.

Best,
Manu

**Comment by hadialqattan** [comment]
Hi, thanks for your help...:heart:

BTW, I have a question, why do you apply `perfect-scrollbar` only on Windows?

**Comment by einazare** [comment]
Hello again, @hadialqattan ,

Well, on Linux, Ubuntu, macOS, and mobile devices, the scrollbars are a bit smoother, and we wanted to make some smoother scrollbars for Windows as well.

**Comment by hadialqattan** [comment]
Thank you pretty much Mr.@EINazare.

**Comment by hamzahoda** [comment]
Hello,

To avoid this issue you can use version 1.4.0 of perfect-scrollbar. Works perfectly with this.
https://demos.creative-tim.com/black-dashboard-react/#/admin/dashboard


you can run
**npm uninstall perfect-scrollbar**
and
**npm i perfect-scrollbar@1.4.0**
