### ISSUE TITLE
[Bug] npm run build produces faulty code

### ISSUE THREAD

**Issue by kmindspark** [creativetimofficial/black-dashboard-react#32]
### Version
1.2.0
### Reproduction link
https://www.creative-tim.com/product/black-dashboard-react
### Operating System
MacOS Big Sur
### Device
MacBook Pro (2019)
### Browser & Version
Chrome: Version 91.0.4472.77 (Official Build) (x86_64)
### Steps to reproduce
1) I downloaded the dashboard and ran npm install, then npm run build to create an optimized version.
2) Then I attempted to serve it with serve -s build but all I see is a whitescreen after going to localhost.
3) However, when running the unoptimized version with npm start, everything works fine. Any ideas as to what this might be?

I'm seeing these errors on the Chrome console. See the image below.
![image](https://user-images.githubusercontent.com/7551261/120907781-3de79000-c619-11eb-9acd-67b9edd012ab.png)
### What is expected?
npm run build should create a working version of the app
### What is actually happening?
npm run build produces a whitescreen with errors in the chrome console.

---
### Additional comments
Minimal reproduction is just the link to your template. Issue happens even with 0 modifications.

**Comment by 0xGREG** [comment]
Remove the "homepage" field from package.json
