### ISSUE TITLE
How to set a focus to an input ?

### ISSUE THREAD

**Issue by softclickbr** [creativetimofficial/black-dashboard-react#33]
### What is your enhancement?
Using normal approaches as ref={refElement} and refElement.current.focus() not works, and I don't know the reason. How to set a focus to a form element i.e. input?

**Comment by sajadevo** [comment]
**Hi @softclickbr**

please use this one `refElement.current.getInputDOMNode().focus();`

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
