### ISSUE TITLE
[Bug] Does not install

### ISSUE THREAD

**Issue by brodypiper** [creativetimofficial/black-dashboard-react#42]
### Version
Latest master in "git clone"
### Reproduction link
https://pastebin.com/Q9JEDXHn
### Operating System
Any
### Device
Any
### Browser & Version
N/A
### Steps to reproduce
1. https://demos.creative-tim.com/black-dashboard-react/#/documentation/tutorial

### What is expected?
The turorial suggests "npm install" should work
### What is actually happening?
"npm install" is not working

---
### Solution
Cross my fingers and hope the dev team is able to solve the issue :-)

### Additional comments
Halppp! :)

**Comment by Aboude-Adra** [comment]
Use `npm install --legacy-peer-deps`
You'll get a bunch of deprecated packages messages but it'll work

**Comment by sajadevo** [comment]
Hey there,

I've released the v1.2.2 and this issue is fixed now.

Regards,
Sajad
