### ISSUE TITLE
Nucleo Icons - Internet Explorer

### ISSUE THREAD

**Issue by Asher978** [creativetimofficial/black-dashboard-react#5]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Nucleo-icons should be visible in all borwsers.

# Current Behavior
Nucleo-icons not being visible with Internet Explorer. They work on all other browsers but the internet explorer

# Failure Information (for bugs)
There are no errors reported. The icons simply do not render.

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

**Comment by einazare** [comment]
Hello there @Asher978 ,

Thank you for your interest in working with our product, and for your concern.
Unfortunately, a few months ago, we've dropped support for Internet Explorer, as you can see in our [README.md here](https://github.com/creativetimofficial/black-dashboard-react#browser-support).
A lot of the major firms and companies have started to drop support for Internet Explorer, so we are just aligning ourselves with everybody.

I am really sorry for my answer.

Best,
Manu
