### ISSUE TITLE
Adding route for login

### ISSUE THREAD

**Issue by piyush97** [creativetimofficial/black-dashboard-react#6]
!!! IF YOU DO NOT USE THIS ISSUES TEMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Unexpected Behavior

Not able to create a route for Login

**Comment by einazare** [comment]
Hello there @piyush97 ,

Please detail. What were the steps that you have taken, and they didn't work?

Best,
Manu

**Comment by j14y** [comment]
In the index.js file in the src/ directory, `ReactDOM.render` is defined as:

```
ReactDOM.render(
  <Router history={hist}>
    <Switch>
      <Route path="/admin" render={props => <AdminLayout {...props} />} />
      <Route path="/rtl" render={props => <RTLLayout {...props} />} />
      <Redirect from="/" to="/admin/dashboard" />
    </Switch>
  </Router>,
  document.getElementById("root")
);
```

By default the dashboard redirects to `/admin/dashboard` when the root url `/` is entered. 

If you want to implement a login/sign-up page, simply change

```
<Redirect from="/" to="/admin/dashboard" />
```

to something like

```
<Redirect from="/" to "/login"/>
```

You'll then have to supply a new route and component to `react-router-dom`, giving something like:

```
<Route path="/login" component={Login}/>
```

Where `Login` is your login view that you want create.

The final code looks like this:

```
ReactDOM.render(
  <Router history={hist}>
    <Switch>
      <Route path="/admin" render={props => <AdminLayout {...props} />} />
      <Route path="/rtl" render={props => <RTLLayout {...props} />} />
      <Route path="/login" component={Login}/>    {/* basically add this line */}
      <Redirect from="/" to="/login" /> {/* and change this line from the default */}
    </Switch>
  </Router>,
  document.getElementById("root")
);
```

Note that the file `routes.js` is used for specifying routes within the dashboard sidebar, so unless you want to add another view to it, it shouldn't be used for creating custom routes.
