### ISSUE TITLE
[Bug] The Options in Select (Form Select) are invisible in dark mode if "custom-select" or "form-control" is used.

### ISSUE THREAD

**Issue by t3chn0tr0n** [creativetimofficial/black-dashboard-react#7]
### Version
Black Dashboard React v1.0.0 based on Black Dashboard - v1.0.0
### Reproduction link
https://demos.creative-tim.com/black-dashboard-react/#/documentation/forms
### Steps to reproduce
<select className="custom-select"> Select
    <option selected>1</option>
    <option>2</option>
</select>

Now open in browser and see the problem.
### What is expected?
All options should be visible without hovering over them.
### What is actually happening?
Options are not visible without hover over.

---

**Comment by einazare** [comment]
Hello there @t3chn0tr0n ,

Thank you for your interest in working with our products.
It seems to me that the selects is working as expected, in both dark and white mode:
![Screen Shot 2019-06-21 at 9 19 45 AM](https://user-images.githubusercontent.com/26245512/59902108-fa80c080-9405-11e9-8596-68f969055d76.png)
![Screen Shot 2019-06-21 at 9 19 54 AM](https://user-images.githubusercontent.com/26245512/59902109-fb195700-9405-11e9-98c2-81510d488e6c.png)

Please provide some more details on the problem.

Best,
Manu

**Comment by its-tn10** [comment]
@EINazare 
I'm not the original person who posted the question, but I've encountered the same issue as well.
I'm currently using the latest version of Firefox on Windows 10, and the documentation for this theme (provided in the first post already) and my environment for development encounters this issue.

![Capture](https://user-images.githubusercontent.com/43159039/60377901-753a7480-99e0-11e9-94e2-79ef5543dd14.PNG)
![Capture2](https://user-images.githubusercontent.com/43159039/60377903-766ba180-99e0-11e9-9287-e502d09b79c6.PNG)

**Comment by einazare** [comment]
Hello there, @t3chn0tr0n , @its-tn10 ,

@its-tn10 , thank you for providing your browser version and OS. I checked and indeed on Windows, the options inside the select are not visible.
To solve it, just add the following code inside your css:
```
select.form-control option {
   color: #888;
}
```

Let me know if that worked.

Best,
Manu

**Comment by its-tn10** [comment]
Yep, the text color changed to a light-grey color and it now works as it should. Thanks!

**Comment by t3chn0tr0n** [comment]
Yay its fixed now.
Btw, This dashboard is a great job done!

**Comment by einazare** [comment]
Hello again, guys,

I will leave this issue opened until I will make a new updated on this product so that I won't forget about it.

Thank you,
Manu

**Comment by t3chn0tr0n** [comment]
okay, no problem.
