### ISSUE TITLE
The footer and navbar are overlapping when wrong path is entered in the url

### ISSUE THREAD

**Issue by Robel-GH** [creativetimofficial/black-dashboard-react#8]
What is expected ?
To raise 404 
![Opera Snapshot_2019-07-08_120124_localhost](https://user-images.githubusercontent.com/52368335/60798683-4c517680-a17a-11e9-8252-ef5e5d5c8b06.png)

**Comment by einazare** [comment]
Hello there, @Robel-GH ,

Thank you for your interest in working with our products.
First of all, let me ask you, why did you not follow our rules?
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/black-dashboard-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->
```

If I had seen that you did not use our issue template, I would have closed your issue without the bellow solution.

This being said, please go inside `src/layouts/Admin/Admin.jsx` and add the following import:
```
import { Redirect } from "react-router-dom";
```
Then, change this line:
```
<Switch>{this.getRoutes(routes)}</Switch>
```
To:
```
<Switch>
   {this.getRoutes(routes)}
  <Redirect from="/admin" to="/path/to/your/404/page" />
</Switch>
```

**Please note that `"/path/to/your/404/page"` you need to change this.**

In our next update we are going to say:
```
<Switch>
   {this.getRoutes(routes)}
  <Redirect from="/admin" to="/admin/dashboard" />
</Switch>
```

Hope this helps.

Best,
Manu
