### ISSUE TITLE
Error npm install node-sass

### ISSUE THREAD

**Issue by ghost** [creativetimofficial/black-dashboard-react#9]
./src/assets/scss/black-dashboard-react.scss (./node_modules/css-loader??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js!./src/assets/scss/black-dashboard-react.scss)
To import Sass files, you first need to install node-sass.
Run `npm install node-sass` or `yarn add node-sass` inside your workspace.
Require stack:
- /Volumes/Mystic/React/black-react/node_modules/sass-loader/lib/loader.js
- /Volumes/Mystic/React/black-react/node_modules/loader-runner/lib/loadLoader.js
- /Volumes/Mystic/React/black-react/node_modules/loader-runner/lib/LoaderRunner.js
- /Volumes/Mystic/React/black-react/node_modules/webpack/lib/NormalModule.js
- /Volumes/Mystic/React/black-react/node_modules/webpack/lib/NormalModuleFactory.js
- /Volumes/Mystic/React/black-react/node_modules/webpack/lib/Compiler.js
- /Volumes/Mystic/React/black-react/node_modules/webpack/lib/webpack.js
- /Volumes/Mystic/React/black-react/node_modules/react-scripts/scripts/start.js

**Comment by einazare** [comment]
closed issue since it does not comply with our rules:
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/black-dashboard-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->
```
